### ISSUE TITLE
发送图片到屏幕上

### ISSUE THREAD

**Issue by istrashguy** [chenxuuu/USB-Screen#3]
怎么将一张图片发送到已经连接好的IPS屏幕上，硬件均为教程一致，没看明白源码提供了什么

**Comment by chenxuuu** [comment]
参考[通信协议](https://github.com/chenxuuu/USB-Screen#%E9%80%9A%E8%AE%AF%E5%8D%8F%E8%AE%AE)与[上位机代码](https://github.com/chenxuuu/USB-Screen/blob/master/ProjectCDC/Client/UsbScreen/Models/SerialScreen.cs#L207)

**Comment by istrashguy** [comment]
抱歉，我对c#语言并不熟悉，但看出了projectcdc目录下的Client文件夹或许是关键，用VS打开UsbScreen.sln文件后我认为MainWindow.xaml.cs，我运行时出现了Newtonsoft.Json包导入失败的问题，请问我以上分析与问题该如何解决，如果我想的不对，还请指出，谢谢!

**Comment by chenxuuu** [comment]
还原一下nuget重新打开工程即可


不会c#的话照着协议手写就行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月16日(周四) 晚上7:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [chenxuuu/USB-Screen] 发送图片到屏幕上 (Issue #3)




 
抱歉，我对c#语言并不熟悉，但看出了projectcdc目录下的Client文件夹或许是关键，用VS打开UsbScreen.sln文件后我认为MainWindow.xaml.cs，我运行时出现了Newtonsoft.Json包导入失败的问题，请问我以上分析与问题该如何解决，如果我想的不对，还请指出，谢谢!

**Comment by istrashguy** [comment]
抱歉再次打扰到你，我按照通信协议的格式设置了数据包，将长宽开始与结束都设置为了239，0 ;但是运行后屏幕无反应，以下为python代码：

# RGB565中 高低位对应二进制
import serial
data_high = 0b00000000  # 0x00
data_low = 0b00011111    # 0x1F
data_length = len(hex(data_high)) + len(hex(data_low))
print(data_length)
width_start = 0
width_end = 239
height_start = 0
height_end = 239

data = bytearray([
    data_length, width_start, width_end, height_start, height_end, data_high, data_low
])
screen = serial.Serial('COM3', 115200, timeout=1)
screen.write(data)

如果哪有错请指出或者给我一份示例代码参考，谢谢
